---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: dffo-bluebuild-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 44 # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    group-install:
      packages:
        - sway-desktop-environment
    install:
      packages:
        - tmux
        - wl-kbptr
        - ripgrep
        - vim
        - emacs
        - fastfetch
        - featherpad
        - rclone
        - dconf-editor
        - racket
        - xwayland-satellite
        - gh
        - pipx
        - samba
        - docker
        - docker-compose
        - runc
        - distrobox
        - freerdp
        - btop
        - chezmoi
        - tldr
        - rsyslog
        - caja
        - caja-open-terminal
        - gvfs-mtp
        - clang
        - clang-tools-extra
        - inotify-tools
        - sysstat
        - iotop-c
        - lm_sensors
        - noctalia
        - gnome-disk-utility
        - virt-manager
        - qemu-kvm
        - qemu
        - libvirt
        - sshfs
        - terminus-fonts-console
        - ddcutil

  - type: dnf
    repos:
      cleanup: true
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - dunst
        - Thunar

  - type: dnf
    repos:
      cleanup: true
      copr:
        - marcelohdez/dim
    install:
      packages:
        - dim-screen

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.belmoussaoui.Decoder
          - com.calibre_ebook.calibre
          - com.github.finefindus.eyedropper
          - com.github.flxzt.rnote
          - com.github.jeromerobert.pdfarranger
          - com.github.k4zmu2a.spacecadetpinball
          - com.github.tchx84.Flatseal
          - com.github.wwmm.easyeffects
          - com.github.xournalpp.xournalpp
          - com.obsproject.Studio
          - com.polyphone_soundfonts.polyphone
          - com.usebottles.bottles
          - com.valvesoftware.Steam
          - com.vixalien.sticky
          - io.github.celluloid_player.Celluloid
          - io.github.flattool.Warehouse
          - io.github.nokse22.ultimate-tic-tac-toe
          - io.github.plrigaux.sysd-manager
          - io.missioncenter.MissionCenter
          - net.sourceforge.dmidiplayer
          - org.DolphinEmu.dolphin-emu
          - org.chromium.Chromium
          - org.develz.Crawl
          - org.gnome.Calendar
          - org.gnome.Chess
          - org.gnome.Evolution
          - org.gnome.Shotwell
          - org.gnome.SimpleScan
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gnome.font-viewer
          - org.inkscape.Inkscape
          - org.kde.ark
          - org.kde.kdenlive
          - org.kde.kweather
          - org.kde.okular
          - org.libreoffice.LibreOffice
          - org.libretro.RetroArch
          - org.pulseaudio.pavucontrol
          - org.remmina.Remmina
          - org.rncbc.qpwgraph
          - org.torproject.torbrowser-launcher
      - scope: user # Also add Flathub user repo, but no user packages

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: systemd
    system:
      enabled:
        - rsyslog.service
        - smb.service
        - nmb.service
        - podman.socket
        - libvirtd.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
